version: "3.9"
services:
  puisiku-client-spa:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
    networks:
      - puisiku

networks:
  puisiku:
    external: true